// Tur yazıları. Yeni cümle eklemek için listeye bir satır ekle.
module.exports = [
  'İzleyeceğin film başlamadan tüm abur cuburlar bitmiştir.',
  'Alarmı kapatıp "bir dakika daha" dedin, saat öğlen oldu.',
  'Sınavdan önceki gece kitabı ilk kez açtın.',
  'Kavurucu sıcakta klima bozuldu.',
  'Telefonun şarjı tam yüzde 1\'de.',
  'Arkadaşın "beş dakikaya oradayım" dedi, bir saattir bekliyorsun.',
  'Hesabı bölüşürken biri yine "ben sadece çay içtim" dedi.',
  'Yeni aldığın telefonu ilk günden düşürdün.',
  'Mesajı yanlış kişiye attığını fark ettin.',
  'Maç, son dakikada yenen golle bitti.',
  'Annen odana girip "bu ne dağınıklık" dedi.',
  'Diyetin ilk günü ve karşında sıcak börek var.',
  'Zam geldi ama maaş aynı kaldı.',
  'Yılbaşı gecesi evde tek başına uyuyakaldın.',
  'Grup ödevini sen yaptın, herkes aynı notu aldı.',
  'Sevdiğin dizinin yeni sezonunu bir arkadaşın spoiler verdi.',
  'Asansörde biriyle göz göze geldin ve kimse konuşmuyor.',
  'Tam sabunlanmışken su kesildi.',
  'Patronun "bir şey konuşalım" dedi.',
  'Pizza bir saattir gelmiyor, kurye telefonu açmıyor.',
  'En sevdiğin tişörtü giyecektin ama üzerinde leke var.',
  'Kimsenin gülmediği espriye kendin güldün.',
  'Uçak rötar yaptı, havalimanında sabahladın.',
  'İlk kez denize girdin ve su buz gibi.',
  'Sürpriz doğum günü partisini yanlışlıkla kendin patlattın.',
  'İnternet tam finalde koptu.',
  'Taksici "yol tarifini sen ver" dedi.',
  'Öğretmen "ödevleri çıkarın" dedi, sen ödevi evde unuttun.',
  'Çayı yeni demledin, tam içecekken döküldü.',
  'Baristanın kahve bardağına adını yanlış yazdığını gördün.',
  'Eski sevgilin aynı mekana geldi.',
  'Yağmur başladı, şemsiyen yok, toplantıya beş dakika var.',
  'Hesabı ödeyeceğin sırada kartın çalışmadı.',
  'Yarın erken kalkacaksın ve saat gece üç.',
  'Buzdolabındaki son kolanın bittiğini ama kutunun durduğunu fark ettin.',
  'Babanın "telefondan fotoğraf nasıl atılır" sorusu geldi.'
];
